### PR TITLE
Update smac_st.zig

### PR DESCRIPTION
**Pull request by arjitGeo**

### CODE REVIEW

**Review by rdoetjes — CHANGES_REQUESTED** [review]
debug is not the same same as standard out. When you rite cli tools, you want to redirect stdout and stderr into the next function.  You want to keep stderr for actual errors.

**Review by rdoetjes — CHANGES_REQUESTED** [review]
debug is not the same same as standard out. When you rite cli tools, you want to redirect stdout and stderr into the next function.  You want to keep stderr for actual errors.

**Comment by arjitGeo** [comment]
> debug is not the same same as standard out. When you rite cli tools, you want to redirect stdout and stderr into the next function. You want to keep stderr for actual errors.

I'm aware of it. I got errors when I tried to compile it with stdout.print(). The stdout has to be declared within the function in order to work. that's why I did that. And does it matter where it's printed?

**Comment by rdoetjes** [comment]
Fascinating, which version are you using?Then it may have been used, and I want to look into that and patch it so it can write to stdout. Sent from my iPhoneOn 10 Oct 2023, at 08:31, Arjit Geo ***@***.***> wrote:﻿

debug is not the same same as standard out. When you rite cli tools, you want to redirect stdout and stderr into the next function. You want to keep stderr for actual errors.

I'm aware of it. I got errors when I tried to compile it with stdout.print(). The stdout has to be declared within the function in order to work. that's why I did that. And does it matter where it's printed?

**Comment by arjitGeo** [comment]
I'm using zig 0.12.0. I talked about this issue on their official [discord.](https://discord.com/channels/605571803288698900/1161192079628697601)

this is the answer I got.

>Your stdout initializer is only valid on linux, it is not comptime-known on windows. 
you should just move the const into main

**Comment by rdoetjes** [comment]
Aaah a Windows incompatibility, that’s weird that its needs to be in a function.
Then again Windows is weird. I’ll merge your patch and die you a mention. 

Thanks!


Raymond Doetjes
Phonax-Soft
***@***.***
Mobile: (+)31 (0)634861945
KvK Utrecht: 52165205
BTW nummer: NL001940134B31

**Comment by arjitGeo** [comment]
Thank you for mentioning!

There's a slight syntax change for truncate function on smac_mt.zig

`@truncate(u32, i)` to `@as(u32, @truncate(i)`

change that too.

**Pull request merged**
